version: '3.1'

services:
  jenkins:
    image: jenkins:2.46.2
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - jenkins_home:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    - ./dtr-ca.crt:/etc/docker/certs.d/159.100.250.45/ca.crt
    - /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:/usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
    - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    networks:
      - build
    deploy:
      placement:
        constraints: [node.labels.node-role == infra]
    labels:
      container-type: "build"

networks:
  build:
    external:
      name: build

volumes:
    jenkins_home:
    
