version: '3.1'

services:
  jenkins:
    image: jenkins:2.46.2
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - jenkins_home:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1.1.0:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
    - /lib/x86_64-linux-gnu/libsystemd-journal.so.0.10.2:/lib/x86_64-linux-gnu/libsystemd-journal.so.0
    - /lib/x86_64-linux-gnu/libcgmanager.so.0.0.0:/lib/x86_64-linux-gnu/libcgmanager.so.0
    - /lib/x86_64-linux-gnu/libnih.so.1.0.0:/lib/x86_64-linux-gnu/libnih.so.1
    - /lib/x86_64-linux-gnu/libnih-dbus.so.1.0.0:/lib/x86_64-linux-gnu/libnih-dbus.so.1
    - /lib/x86_64-linux-gnu/libgcrypt.so.11.8.2:/lib/x86_64-linux-gnu/libgcrypt.so.11
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    - ./ucp:/ucp
    - ./dtr-ca.crt:/etc/docker/certs.d/159.100.250.45/ca.crt
    networks:
      - build
    deploy:
      placement:
        constraints: [node.labels.node-role == infra]
    labels:
      container-type: "build"

networks:
  build:
    external:
      name: build

volumes:
    jenkins_home:
    