version: '3.1'

services:
  jenkins:
    image: jenkins:2.46.2
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - /root/git/jenkins-data:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    - /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:/usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
    - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    - /root/dtr_ca.crt:/etc/docker/certs.d/registry.demo.cloudcontrolled.net/ca.crt
    networks:
      - build
    deploy:
      placement:
        constraints: [node.labels.node-role == infra]
    labels:
      container-type: "build"

networks:
  build:

volumes:
    jenkins_home:
    
